---
label: Product
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: Name
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: images
  type: image_gallery
  config: {}
  label: Images
pages:
- content/products/product-a.md
