---
label: Project
hide_body: true
fields:
- name: project_name
  type: text
  config:
    required: false
  label: Project Name
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: photos
  type: image_gallery
  config: {}
  label: Photos
- name: related_products
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: pages
      section: products
  label: Related Products
